---
- name: This is a test for ale_aos_command module
  hosts: alcatel
  connection: local
  roles:
    - gmoisio.ale_aos
  vars:
    ansible_python_interpreter: "python"
  tasks:
    - name: Add vlan {{ vlan_name }} with vid {{ vlan_id }}
      ale_aos_command:
        host: "{{ inventory_hostname }}"
        username: "{{ login }}"
        password: "{{ password }}"
        command: vlan {{ vlan_id }} enable name {{ vlan_name }}
    - name: Get Vlan port
      ale_aos_command:
        host: "{{ inventory_hostname }}"
        username: "{{ login }}"
        password: "{{ password }}"
        command: show vlan port
        timing: True
      register: vlan_list
    - name: Select only trunk port
      vars:
        array: "{{ vlan_list.output.split('\n') }}"
      set_fact:
        vlan_sorted: "{{ vlan_sorted | default([]) + [item]}}"
      loop: "{{ array }}"
      when: "'qtagged' in item"
    - name: Select only interfaces name
      set_fact:
        trunk_port: "{{ trunk_port | default([]) + [item.split(' ') | Select()]}}"
      loop: "{{vlan_sorted}}"
    - name: Show interfaces
      debug:
        var: trunk_port
