---
- name: This is a test for ale_aos_command module
  hosts: alcatelTest
  connection: local
  roles:
    - gmoisio.ale_aos
  vars:
    ansible_python_interpreter: "python"
  tasks:
    - name: Get vlan port
      ale_aos_command:
        host: "{{ inventory_hostname }}"
        username: "{{ switch_username }}"
        password: "{{ switch_password }}"
        command: show vlan port
        timing: True
      register: ports
    - name: Parse data
      ansible.utils.cli_parse:
        text: "{{ ports.output }}"
        parser:
          name: ansible.utils.textfsm
          template_path: ./templates/alcatel_show_vlan_port.textfsm
        set_fact: ports_parsed
    - name: Group data
      ansible.builtin.group_by:
        key: PORT
        parents:
          - "{{ ports_parsed }}"
      register: result
    - name: Display result
      debug:
        var: result
