---
- name: This is a test for ale_aos_command module
  hosts: alcatelTest
  connection: local
  roles:
    - gmoisio.ale_aos
  vars:
    ansible_python_interpreter: "python"
  tasks:
    - name: Get vlan port
      ale_aos_command:
        host: "{{ inventory_hostname }}"
        username: "{{ switch_username }}"
        password: "{{ switch_password }}"
        command: show vlan port
      register: ports
    - name: Parse to JSON
      ansible.utils.cli_parse:
        command: ports | json
        parser:
          name: ansible.utils.json
        register: ports_parsed
    - name: Display result
      debug:
        var: ports_parsed
