---
- name: Test Playbook for ale_aos_ping module
  hosts: ale
  connection: local
  gather_facts: no
  roles:
    - gmoisio.ale_aos
  vars:
    ansible_python_interpreter: "python"
  tasks:
    - name: Test ale_aos_ping Python module
      ale_aos_ping:
        host: "{{ inventory_hostname }}"
        username: "{{ login }}"
        password: "{{ password }}"
