---
- name: This is a test for ale_aos_command module
  hosts: alcatelTest
  connection: local
  roles:
    - gmoisio.ale_aos
  vars:
    ansible_python_interpreter: "python"
  tasks:
    - name: Add vlan {{ vlan_name }} with vid {{ vlan_id }}
      ale_aos_command:
        host: "{{ inventory_hostname }}"
        username: "{{ switch_username }}"
        password: "{{ switch_password }}"
        command: vlan {{ vlan_id }} enable name {{ vlan_name }}
    - name: Get Vlan port
      ale_aos_command:
        host: "{{ inventory_hostname }}"
        username: "{{ switch_username }}"
        password: "{{ switch_password }}"
        command: show vlan port
        timing: True
      register: vlan_list
    - name: Select only trunk port
      vars:
        array: "{{ vlan_list.output.split('\n') }}"
      set_fact:
        vlan_sorted: "{{ vlan_sorted | default([]) + [item]}}"
      loop: "{{ array }}"
      when: "'qtagged' in item"
    - name: Select only interfaces name
      set_fact:
        trunk_port: "{{ trunk_port | default([]) + [item.split(' ')[5]]}}"
      loop: "{{vlan_sorted}}"
    - name: Add new vlan to trunk
      vars:
        ports: "{{ trunk_port | unique }}"
      ale_aos_command:
        host: "{{ inventory_hostname }}"
        username: "{{ switch_username }}"
        password: "{{ switch_password }}"
        command: vlan {{ vlan_id }} 802.1q {{ ports | join(' ') }}
        timing: True
# Voir LLDP pour la découverte de ports
