---
- name: Playbook to export alcatel switch configuration to a Samba folder
  hosts: alcatel
  connection: local
  roles:
    - gmoisio.ale_aos
  vars:
    ansible_python_interpreter: "python"
  tasks:
    - name: Get configuration from switch
      ale_aos_command:
        host: "{{ inventory_hostname }}"
        username: "{{ switch_username }}"
        password: "{{ switch_password }}"
        timing: True
        command: "show configuration snapshot"
      register: config
    - name: Create a configuration file
      copy:
        content: "{{ config.output }}"
        dest: "/home/public/export_conf_brutes/{{ inventory_hostname }}.cfg"

    - name: Get Timestamp from the system
      shell: "date +%Y-%m-%d%H-%M-%S"
      register: tstamp

    - name: Create a folder for the day
      ansible.builtin.command:
        cmd: "smbclient {{ samba_share }} -U 'PBNA\\\\{{ smb_user }}%{{ smb_password }}' -c 'cd \"{{ source_folder }}\" ; mkidr {{ tstamp.stdout[0:10] }}'"

    - name: Copy configuration file to Samba Folder
      ansible.builtin.command:
        cmd: "smbclient {{ samba_share }} -U 'PBNA\\\\{{ smb_user }}%{{ smb_password }}' -c 'cd \"{{ source_folder }}\\{{ tstamp.stdout[0:10] }}\" ; put \"/home/public/export_conf_brutes/{{ inventory_hostname }}.cfg\" {{ inventory_hostname }}.cfg'"

    - name: Clean files
      ansible.builtin.command:
        cmd: rm -rf "/home/public/export_conf_brutes/{{ inventory_hostname }}.cfg"
