---
- name: This is a test for ale_aos_command module
  hosts: ale
  connection: local
  roles:
    - gmoisio.ale_aos
  vars:
    ansible_python_interpreter: "python"
  tasks:
    - name: Add vlan {{ vlan_name }} with vid {{ vlan_id }}
      ale_aos_command:
        host: "{{ inventory_hostname }}"
        username: "{{ login }}"
        password: "{{ password }}"
        command: vlan {{ vlan_id }} enable name {{ vlan_name }}
    - name: Get Vlan list
      ale_aos_command:
        host: "{{ inventory_hostname }}"
        username: "{{ login }}"
        password: "{{ password }}"
        command: show vlan
        timing: True
      register: vlan_list
    - name: Display Vlan List
      debug:
        mdsg: "{{ vlan_list }}"
