---
- name: This command remove vlan on alcatel switches
  hosts: alcatelTest
  connection: local
  roles:
    - gmoisio.ale_aos
  vars:
    ansible_python_interpreter: "python"
  tasks:
    - name: Remove vlan {{ vlan_id }}
      ale_aos_command:
        host: "{{ inventory_hostname }}"
        username: "{{ switch_username }}"
        password: "{{ switch_password }}"
        command: no vlan {{ vlan_id }}
    - name: Get Vlan list
      ale_aos_command:
        host: "{{ inventory_hostname }}"
        username: "{{ switch_username }}"
        password: "{{ switch_password }}"
        command: show vlan
        timing: True
      register: vlan_list
    - name: Display Vlan List
      debug:
        msg: "{{ vlan_list.output }}"
